# 我的数据服从正态分布吗？

> 原文：<https://towardsdatascience.com/do-my-data-follow-a-normal-distribution-fb411ae7d832?source=collection_archive---------5----------------------->

## 关于最广泛使用的分布以及如何检验 R 中的正态性的一个注记

![](img/d070ebfaa95ebf1ebbd34bc9b828343c.png)

摄影:Tra Nguyen

# 什么是正态分布？

T 正态分布是定义一组测量值如何围绕这些测量值的中心(即平均值)分布的函数。现实生活中的许多自然现象可以用钟形频率分布来近似，这种分布称为正态分布或高斯分布。

正态分布是一种山形、单峰和对称分布，其中大多数测量值聚集在平均值附近。此外，一个指标偏离均值越远，发生的概率就越低。从这个意义上说，对于一个给定的变量，找到接近平均值的值是很常见的，但随着我们远离平均值，找到值的可能性越来越小。最后但同样重要的是，由于正态分布是围绕其均值对称的，所以分布的两个尾部都不太可能出现极值。例如，假设成年人的身高遵循正态分布，大多数成年人接近平均身高，极矮的成年人和极高的成年人一样不常见。

在本文中，重点是了解正态分布、相关的经验规则、其参数以及如何计算 Z 得分以找到曲线下的概率(用示例说明)。由于这是一些统计检验的要求，我们也给出了 4 种互补的方法来检验 r 中的正态性假设。

# 经验法则

具有近似正态分布的数据具有明确的变化，如以下经验规则所示:

*   μ σ包括大约 68%的观测值
*   μ 2⋅σ包括大约 95%的观测值
*   μ 3⋅σ包含了几乎所有的观测值(更精确地说是 99.7%)

![](img/1ee706726af3f249e26f1a4bf9ff1b5b.png)

正态分布和经验法则(68–95–99.7%法则)

其中，μ和σ分别对应于总体均值和总体标准差。

经验法则，也称为 68–95–99.7%法则，通过下面两个例子来说明。假设已知比利时一所大学所有学生的统计学考试成绩大致呈正态分布，均值μ=67，标准差σ=9。然后可以推断，大约 68%的分数在 58 和 76 之间，大约 95%的分数在 49 和 85 之间，并且几乎所有的分数(99.7%)在 40 和 94 之间。因此，知道了平均值和标准差，我们就能很好地了解分数的分布情况。现在假设从参加考试的人中随机抽取一名大学生。她的分数在 49 到 85 之间的概率有多大？基于经验法则，我们发现 0.95 是这个概率问题的合理答案。

经验法则的效用和价值是由于自然界中普遍存在近似正态分布的测量值。比如智商，鞋码，身高，出生体重等。近似呈正态分布。你会发现，大约 95%的测量值在其平均值的 2σ以内(Wackerly、Mendenhall 和 Scheaffer，2014 年)。

# 因素

像许多概率分布一样，正态分布的形状和概率完全由一些参数定义。正态分布有两个参数:(I)[均值μ](https://www.statsandr.com/blog/descriptive-statistics-by-hand/#mean) 和(ii)[方差σ^2](https://www.statsandr.com/blog/descriptive-statistics-by-hand/#variance) (即[标准差σ](https://www.statsandr.com/blog/descriptive-statistics-by-hand/#standard-deviation) 的平方)。均值μμ定位了分布的中心，即观测值的中心趋势，方差σ^2 定义了分布的宽度，即观测值的展宽。

均值μμ可以取任意有限值(即∞ < μ < ∞), whereas the variance σ^2 can assume any positive finite value (i.e., σ^2 > 0)。正态分布的形状基于这两个参数而变化。由于均值和方差的组合有无限多种，所以正态分布也有无限多种，因此也有无限多种形式。

例如，查看当两个参数改变时，正态分布的形状如何变化:

![](img/18b2125666ae424b547cadc2083c302a.png)![](img/8c2a7879eb8d1ec0664f2951eff67c25.png)

正如你在第二张图中看到的，当方差(或标准差)减小时，观察值更接近平均值。相反，当方差(或标准差)增加时，观察值更有可能远离均值。

服从均值为 430、方差为 17 的正态分布的随机变量 x 表示为 x∞n(μ= 430，σ^2 = 17)。

我们已经看到，尽管不同的正态分布有不同的形状，但所有的正态分布都有共同的特征:

*   它们是对称的，50%的人口高于平均值，50%的人口低于平均值
*   平均值、中值和众数相等
*   前面详述的经验法则适用于所有的正态分布

# 概率和标准正态分布

正态分布的随机变量的概率和分位数可以通过函数`pnorm()`和`qnorm()`使用 R 很容易地找到。使用这个[闪亮的应用程序](https://antoinesoetewey.shinyapps.io/statistics-101/)，也可以找到与正态分布相关的概率。但是，在计算概率之前，我们需要了解更多关于标准正态分布和 Z 得分的信息。

虽然正态分布有无限多种(因为均值和方差的每种组合都有一个正态分布)，但我们只需要一张表就可以找到正态曲线下的概率:**标准正态分布**。正态标准分布是正态分布的特殊情况，其中平均值等于 0，方差等于 1。正态随机变量 X 总是可以转换为标准正态随机变量 Z，这个过程称为“缩放”或“标准化”，方法是从观察值中减去平均值，然后将结果除以标准偏差。形式上:

![](img/610ec989f14fb6ba84a6205ce2b7c903.png)

其中 X 是观测值，μμ和σσ是从中抽取观测值的总体的平均值和标准差。所以标准正态分布的均值是 0，方差是 1，记为 z∞n(μ= 0，σ^2 = 1)。

从这个公式中，我们看到 Z，称为标准分数或 Z 分数，允许看到一个特定的观察值与所有观察值的平均值有多远，距离用标准偏差表示。换句话说，Z 分数对应于一次观察偏离平均值的标准偏差数。正的 Z 值意味着特定的观察值高于平均值，而负的 Z 值意味着特定的观察值低于平均值。z 分数经常被用来比较一个人和她的同龄人，或者更一般地，一种与其分布相比的度量。

例如，假设一名学生在统计学考试中得了 60 分，班级的平均分数为 40 分，在经济学考试中得了 65 分，班级的平均分数为 80 分。考虑到“原始”分数，有人会说这个学生在经济学方面比在统计学方面表现更好。然而，考虑到她的同龄人，很明显，这名学生在统计学方面的表现相对好于经济学。计算 Z 分数允许考虑所有其他学生(即，整个分布)并给出更好的比较度量。让我们计算两次考试的 Z 分数，假设两次考试的分数遵循具有以下参数的正态分布:

![](img/3d95b0fcff9f9155ddf19c17dce497ea.png)

z 分数为:

![](img/31a39bd9883e8b2ed80b08a8da6d9a03.png)

一方面，统计学考试的 Z 分数是正的(Zstat = 2.5)，这意味着她比平均水平表现得更好。另一方面，她在经济学考试中的分数是负的(Zecon = 1.2)，这意味着她的表现比平均水平差。为了便于比较，下面是她在标准正态分布中的成绩:

![](img/80195027711eea9725224d931a059863.png)

虽然经济学的分数从绝对意义上来说更好，但统计学的分数在比较每个分数在自己的分布范围内时，实际上相对更好。

此外，Z score 还能够比较观察值，否则这是不可能的，因为它们具有不同的单位。假设你想比较€的工资和公斤体重。没有标准化，就没有办法断定一个人是在她的工资方面更极端还是在她的体重方面更极端。多亏了 Z 分数，我们可以比较两个原本不可比较的值。

关于 Z 值解释的最后说明:经验法则是 Z 值在-3 和-2 之间或在 2 和 3 之间的观察值被认为是一个罕见值。Z 值小于-3 或大于 3 的观察值被认为是极其罕见的值。具有任何其他 Z 值的值被认为既不罕见也不极其罕见。

# 正态分布下的面积 R 和手动

现在我们已经了解了 Z 分数，我们将使用它来确定正态分布曲线下的面积。

*请注意，在下面的练习中，有几种方法可以找到答案。因此，除了给出的步骤之外，您还可以使用其他步骤来获得相同的结果。*

# 《出埃及记》一

设 Z 表示均值为 0，标准差为 1 的正态随机变量，求 P(Z > 1)。

我们实际上是在下图中寻找阴影区域:

![](img/a15a535a745488774e68fd0414f694d9.png)

标准正态分布:P(Z > 1)

## 在 R 中

```
pnorm(1,
  mean = 0,
  sd = 1, # sd stands for standard deviation
  lower.tail = FALSE
)## [1] 0.1586553
```

我们寻找 Z 大于 1 的概率，因此我们设置自变量`lower.tail = FALSE`。默认的`lower.tail = TRUE`将给出 P(Z < 1)的结果。注意 P(Z = 1) = 0 所以写 P(Z > 1)或者 P(Z ≥ 1)是等价的。

## 用手

看到随机变量 Z 已经有了均值 0 和标准差 1，所以不需要变换。要手动计算概率，我们需要参考下图所示的标准正态分布表:

![](img/d864b3e876231607c6181f00cd52e865.png)

标准正态分布表(Wackerly、Mendenhall 和 Scheaffer，2014 年)。

从表顶部的图示中，我们可以看到表中的值对应于某个 Z 上的正态曲线**下的区域。因为我们正在精确地查看 z = 1 以上的概率(因为我们寻找 P(Z > 1))，所以我们可以简单地沿着表中的第一(Z)列向下，直到 z = 1.0。概率是 0.1587。因此，P(Z > 1) = 0.1587。这与我们使用 R 得到的结果相似，只是表中的值被四舍五入为 4 位数。**

# 《出埃及记》2

设 Z 表示均值为 0、标准差为 1 的正态随机变量，求 P(1≤Z≤1)。

我们正在寻找下图中的阴影区域:

![](img/3ca567bb289bb0e93958cb4b4fe545a1.png)

标准正态分布:P(1≤Z≤1)

## 在 R 中

```
pnorm(1, lower.tail = TRUE) - pnorm(-1, lower.tail = TRUE)## [1] 0.6826895
```

注意，默认情况下，平均值和标准偏差的自变量是`mean = 0`和`sd = 1`。既然这是我们需要的，我们可以省略它们。 [1](https://www.statsandr.com/blog/do-my-data-follow-a-normal-distribution-a-note-on-the-most-widely-used-distribution-and-how-to-test-for-normality-in-r/#fn1)

## 用手

在这个练习中，我们按步骤进行:

1.  阴影区域对应于正常曲线下的整个区域减去曲线两端的两个白色区域。
2.  我们知道正态分布是对称的。
3.  因此，阴影区域是曲线下的整个区域减去曲线右尾部的白色区域的两倍，曲线右尾部的白色区域是 P(Z > 1)。
4.  我们也知道正态曲线下的整个面积是 1。
5.  因此，阴影区域是 1 减去 2 乘以 P(Z > 1):

p(1≤z≤1)= 1 2⋅p(z > 1)= 1 2⋅0.1587 = 0.6826

其中 P(Z > 1) = 0.1587 已在前面的练习中找到。

# 《出埃及记》3

设 Z 表示均值为 0，标准差为 1 的正态随机变量，求 P(0 ≤ Z ≤ 1.37)。

我们正在寻找下图中的阴影区域:

![](img/f79c58e1b770dc8e9b12acc0e441f5de.png)

标准正态分布:P(0 ≤ Z ≤ 1.37)

## 在 R 中

```
pnorm(0, lower.tail = FALSE) - pnorm(1.37, lower.tail = FALSE)## [1] 0.4146565
```

## 用手

我们再次按步骤进行这个练习:

1.  我们知道 P(Z > 0) = 0.5 因为曲线下的整个面积是 1，它的一半是 0.5。
2.  阴影面积是曲线下整个面积的一半减去从 1.37 到无穷大的面积。
3.  从 1.37 到无穷大的曲线下面积对应 P(Z > 1.37)。
4.  因此，阴影区域为 0.5 P(Z > 1.37)。
5.  要找到 P(Z > 1.37)，请沿着表中的 Z 列向下找到条目 1.3，然后穿过表的顶部找到标有. 07 的列，得到 P(Z > 1.37)=.0853
6.  因此，

P(0≤Z≤1.37)= P(Z > 0)-P(Z > 1.37)= 0.5 0.0853 = 0.4147

# 《出埃及记》四

回顾一下经验法则中的例子:假设比利时一所大学所有学生的统计学考试成绩呈正态分布，均值μ = 67，标准差σ = 9。分数的多少在 70 和 80 之间？

我们正在寻找下图中的阴影区域:

![](img/3db067adc28648a8b4acebeae94c657a.png)

P(70 ≤ X ≤ 80)其中 x∞n(μ= 67，σ^2 = 9^2)

## 在 R 中

```
pnorm(70, mean = 67, sd = 9, lower.tail = FALSE) - pnorm(80, mean = 67, sd = 9, lower.tail = FALSE)## [1] 0.2951343
```

## 用手

提醒一下，我们要找的是 P(70 ≤ X ≤ 80)其中 x∞n(μ= 67，σ^2 = 9^2).随机变量 x 是“原始”格式，这意味着它还没有被标准化，因为平均值是 67，方差是 9^2.因此，我们需要首先使用以下公式应用变换来标准化端点 70 和 80:

![](img/e0143fe0ef6db32f209fbaf86e207dc0.png)

标准化后，x = 70 变成(就 z 而言，因此就以标准差表示的与平均值的偏差而言):

![](img/d9b7592b6be13538dca2cb37745c6be8.png)

并且 x = 80 变成:

![](img/54e46d76df99121dc35f07844ea36ad8.png)

上面用 X 表示的数字现在用 Z 表示:

![](img/b18a84b18007fffcd9980f5b4f310072.png)

P(0.3333 ≤ Z ≤ 1.4444)其中 z∞n(μ= 0，σ^2 = 1)

求概率 P(0.3333 ≤ Z ≤ 1.4444)类似于练习 1 至练习 3:

1.  阴影区域对应于从 z = 0.3333 到 z = 1.4444 的曲线下的区域。
2.  换句话说，阴影面积就是从 z = 0.3333 到无穷大的曲线下面积减去从 z = 1.4444 到无穷大的曲线下面积。
3.  从表中可以看出，P(Z > 0.3333) = 0.3707，P(Z > 1.4444) = 0.0749。
4.  因此:

P(0.3333≤Z≤1.4444)= P(Z > 0.3333)-P(Z > 1.4444)= 0.3707 0.0749 = 0.2958

与 R 中使用的概率的差异来自舍入。

总结这个练习，我们可以说，假设平均分数是 67，标准差是 9，29.58%的学生得分在 70 到 80 之间。

# 《出埃及记》5

参见上下文[中的另一个例子](https://www.statsandr.com/blog/a-guide-on-how-to-read-statistical-tables/#example)。

# 为什么正态分布在统计学中如此重要？

正态分布很重要，有三个主要原因:

*   一些统计假设检验假设数据遵循正态分布
*   中心极限定理指出，对于大量的观察值(n > 30)，无论原始变量的基本分布是什么，样本均值和总和(Sn = ∑Xi)的分布都可以用正态分布来逼近
*   线性和非线性回归假设残差是正态分布的

因此，知道如何检验 R 的正态性是有用的，这是下一节的主题。

# 如何检验正态假设

如上所述，一些统计测试要求数据遵循正态分布，否则测试结果可能有缺陷。

在本节中，我们将展示 4 种互补的方法来确定您的数据是否遵循 r 中的正态分布。

# 柱状图

直方图显示分布的分布和形状，因此它是评估正态性的良好起点。让我们来看看我们期望遵循正态分布的分布直方图，1，000 个成年人的身高，单位为厘米:

![](img/2837997d76ed937dfdcc9d7689902a79.png)

具有相应平均值和方差的正态曲线已添加到直方图中。直方图遵循正态曲线，因此数据似乎遵循正态分布。

在数据集`iris`的 R 中直方图的最小代码以下:

```
data(iris)
hist(iris$Sepal.Length)
```

![](img/e4e073268480f97c4929607f407cabc8.png)

在`[{ggplot2}](https://www.statsandr.com/blog/graphics-in-r-with-ggplot2/)`中:

```
ggplot(iris) +
  aes(x = Sepal.Length) +
  geom_histogram()
```

![](img/7bb7141a98aaaf75f08dc4624048debf.png)

然而，直方图是不够的，特别是在小样本的情况下，因为箱的数量极大地改变了它的外观。当观察值少于 20 时，不建议使用直方图，因为直方图并不总是正确地显示分布。请参见下面两个包含 10 个和 12 个观察值的数据集的示例:

![](img/5077634bf6cddc1248a4d7a38bdd70f9.png)![](img/a53e25c045a6d60b322a0f1edfe10be6.png)

你能说出这些数据集是否遵循正态分布吗？令人惊讶的是，两者都遵循正态分布！

在本文的剩余部分，我们将使用 12 个成年人的数据集。如果您想在自己的脚本中遵循我的代码，下面是我生成数据的方式:

```
set.seed(42)
dat_hist <- data.frame(
  value = rnorm(12, mean = 165, sd = 5)
)
```

`rnorm()`函数根据正态分布生成随机数(在本例中，12 个随机数的平均值为 165，标准偏差为 5)。这 12 次观察结果被保存在名为`dat_hist`的数据集中，变量为`value`。注意`set.seed(42)`对于获得与 me 完全相同的数据很重要。 [2](https://www.statsandr.com/blog/do-my-data-follow-a-normal-distribution-a-note-on-the-most-widely-used-distribution-and-how-to-test-for-normality-in-r/#fn2)

# 密度图

密度图还提供了对数据是否遵循正态分布的直观判断。它们类似于直方图，因为它们也允许分析分布的分布和形状。然而，它们是直方图的平滑版本。这是从上面讨论的 12 个成年人的身高数据集中绘制的密度图:

```
plot(density(dat_hist$value))
```

![](img/2b8134c8553757aeec2b055b42011655.png)

在`{ggpubr}`中:

```
library("ggpubr") # package must be installed first
ggdensity(dat_hist$value,
  main = "Density plot of adult height",
  xlab = "Height (cm)"
)
```

![](img/a3ae96f0677baec9f68de1c3f88d439a.png)

由于仅从直方图和密度图很难检验正态性，建议用 QQ 图来证实这些图。QQ 图，也称为正态图，是评价正态性的第三种方法。

# QQ 图

像直方图和密度图一样，QQ 图可以直观地评估正态性假设。这是从上面讨论的 12 个成年人的身高数据中得出的 QQ 图:

```
library(car)
qqPlot(dat_hist$value)
```

![](img/eaa0cd9c24e295b26536a4c892378364.png)

```
## [1] 12  2
```

在`{ggpubr}`中:

```
library(ggpubr)
ggqqplot(dat_hist$value)
```

![](img/a39b869295657b98f0f86b6bf00861a6.png)

不需要查看数据的分布(直方图和密度图就是这种情况)，使用 QQ 图，我们只需要确定数据点是否遵循这条线(有时称为亨利线)。

如果点靠近参考线并在置信带内，则可认为满足正态性假设。点和参考线之间的偏差越大，并且它们越位于置信带之外，满足正态条件的可能性就越小。这 12 个成年人的身高似乎遵循正态分布，因为所有点都在置信带内。

当面临非正态分布时，如下面的 QQ 图所示(系统偏离参考线)，第一步通常是对数据应用对数变换，并重新检查以查看经过对数变换的数据是否正态分布。应用对数变换可以通过`log()`函数来完成。

![](img/03ba566505f224c5546409af23cc1aac.png)

请注意，QQ 图也是评估回归分析的残差是否遵循正态分布的一种便捷方式。

# 正规性检验

上面介绍的 3 种工具是对正态性的目视检查。尽管如此，目视检查有时可能不可靠，因此也可以通过统计测试正式测试数据是否遵循正态分布。这些正态性检验将数据的分布与正态分布进行比较，以评估观察值是否与正态分布有重大偏差。

两种最常见的正态性检验是夏皮罗-维尔克检验和科尔莫戈罗夫-斯米尔诺夫检验。两种测试都有相同的假设，即:

*   H0:数据服从正态分布
*   H1:数据不符合正态分布

夏皮罗-维尔克检验被推荐用于正态性检验，因为它提供了比科尔莫戈罗夫-斯米尔诺夫检验更好的功效。 [3](https://www.statsandr.com/blog/do-my-data-follow-a-normal-distribution-a-note-on-the-most-widely-used-distribution-and-how-to-test-for-normality-in-r/#fn3) 在 R 中，夏皮罗-维尔克正态性检验可以用函数`shapiro.test()` : [4](https://www.statsandr.com/blog/do-my-data-follow-a-normal-distribution-a-note-on-the-most-widely-used-distribution-and-how-to-test-for-normality-in-r/#fn4) 来完成

```
shapiro.test(dat_hist$value)## 
##  Shapiro-Wilk normality test
## 
## data:  dat_hist$value
## W = 0.93968, p-value = 0.4939
```

从输出中，我们看到 p 值> 0.05，这意味着我们不拒绝数据遵循正态分布的零假设。该测试与 QQ 图的方向相同，QQ 图没有显示出显著偏离正态性(因为所有点都在置信带内)。

值得注意的是，在实践中，正态性检验通常被认为过于保守，因为对于大样本量(n > 50)，与正态性的微小偏差都可能导致违反正态性条件。正态性检验是一种假设检验，因此随着样本量的增加，它们检测较小差异的能力也增加。因此，随着观察次数的增加，夏皮罗-维尔克检验变得非常敏感，甚至对正态分布的微小偏离也是如此。因此，根据正态性检验，数据不符合正态分布，尽管偏离正态分布的情况可以忽略不计，但数据实际上符合正态分布。因此，通常情况下，正态性条件是基于本文中介绍的所有方法的组合来验证的，即目视检查(使用直方图和 QQ 图)和正式检查(例如，使用夏皮罗-维尔克检验)。

相对于直方图和正态性检验，我个人更倾向于 QQ 图，这样我就不用担心样本大小了。本文展示了可用的不同方法，您的选择当然取决于您的数据类型和您的分析环境。

感谢阅读。我希望这篇文章能帮助你了解更多关于正态分布的知识，以及如何检验 r 中的正态性。

和往常一样，如果您有与本文主题相关的问题或建议，请将其添加为评论，以便其他读者可以从讨论中受益。

**相关文章:**

*   [安装和加载 R 包的有效方法](https://www.statsandr.com/blog/an-efficient-way-to-install-and-load-r-packages/)
*   [R 中的费雪精确检验:小样本的独立性检验](https://www.statsandr.com/blog/fisher-s-exact-test-in-r-independence-test-for-a-small-sample/)
*   [R 中独立性的卡方检验](https://www.statsandr.com/blog/chi-square-test-of-independence-in-r/)
*   [如何在简历中创建时间线](https://www.statsandr.com/blog/how-to-create-a-timeline-of-your-cv-in-r/)

# 参考

威克利、丹尼斯、威廉·门登霍尔和理查德·L·谢弗。2014.*数理统计与应用*。Cengage 学习。

*原载于 2020 年 1 月 29 日 https://statsandr.com*[](https://statsandr.com/blog/do-my-data-follow-a-normal-distribution-a-note-on-the-most-widely-used-distribution-and-how-to-test-for-normality-in-r/)**。**